spring:
  datasource:
    one:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/test1?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        pool-name: mysql-example-cp
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
    two:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3309/test2?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1234
      hikari:
        auto-commit: false
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        pool-name: mysql-example2-cp
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
